Trabajo Practico Nª1

In [2]:
import numpy as np

punto 1

In [5]:
#punto1

lista = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
array = np.array(lista)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


punto 2

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Punto 3

In [11]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

punto 4

In [15]:
arreglo1= np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print(arreglo1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

punto 5

In [18]:


arreglo = np.arange(1, 13)   # del 1 al 12
matriz = arreglo.reshape(3, 4)  # 3 filas, 4 columnas

print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Punto 6

In [ ]:
arregloOrig=  np.array([12, 45, 7, 23, 56, 89, 34])
print(arregloOrig)

ArrPromedio= np.mean(arregloOrig)

print(f"{ArrPromedio} Es el arreglo promedio de {arregloOrig}")


arrmax= np.max(arregloOrig)

print(f"{arrmax} es el valor maximo del arreglo: {arregloOrig}")

arrmin= np.min(arregloOrig)

print(f"{arrmin} es el valor minimo del arreglo: {arregloOrig}")

[12 45  7 23 56 89 34]
38.0 Es el arreglo promedio de [12 45  7 23 56 89 34]
89 es el valor maximo del arreglo: [12 45  7 23 56 89 34]
7 es el valor maximo del arreglo: [12 45  7 23 56 89 34]


Punto 7 Crear dos arrays A=[1,2,3,4,5] y B=[10,20,30,40,50]. Calcular suma, resta, multiplicación y división
elemento a elemento


In [16]:
A=np.array([1,2,3,4,5]) 
B=np.array([10,20,30,40,50])

print(A+B)

print(A-B)

print(A*B)

print(A/B)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


Punto 8 Dado el array [3, 8, 15, 20, 7, 12, 18, 1], obtener un nuevo array con los valores mayores a 10


In [4]:
Arreglo1= np.array([3, 8, 15, 20,10 ,7, 12, 18, 1])
Arreglo2= np.array([])


for a in Arreglo1:
    if a>= 10:
        Arreglo2= np.append(Arreglo2, a)

print(Arreglo1, Arreglo2)

[ 3  8 15 20 10  7 12 18  1] [15. 20. 10. 12. 18.]


Punto 9 Crear una matriz 4x4 con números del 1 al 16. Extraer la segunda fila, la tercera columna y el elemento
(2,2)

In [6]:
arreglo = np.arange(1, 17)  
matriz = arreglo.reshape(4, 4)  

print(matriz)


Seg_Fila= matriz[1]

terce_col= matriz[:,2]

elemento= matriz[2,2]

print(Seg_Fila,terce_col,elemento)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8] [ 3  7 11 15] 11


punto 10Crear una matriz 3x3 con números aleatorios entre 1 y 10. Calcular la suma de cada fila y de cada
columna.


In [13]:

arreglo = np.random.choice(10, size=9, replace=False)
matriz= arreglo.reshape(3,3)



print(matriz)

suma_filas = np.sum(matriz, axis=1)

# Suma de cada columna (axis=0)
suma_columnas = np.sum(matriz, axis=0)

print("\nSuma de cada fila:", suma_filas)
print("Suma de cada columna:", suma_columnas)

[[1 0 3]
 [7 9 8]
 [2 6 4]]

Suma de cada fila: [ 4 24 12]
Suma de cada columna: [10 15 15]


 Dado el array [2,5,8,11,14,17], reemplazar los valores mayores a 10 por -1.

In [18]:
Arreglo1= np.array([2,5,8,11,14,17])


for a in range(len(Arreglo1)):
    if Arreglo1[a]>= 10:
        Arreglo1[a] = -1

print(Arreglo1)

[ 2  5  8 -1 -1 -1]


12. Crear un array con números del 1 al 30 y obtener un nuevo array que contenga solo los números
pares

In [ ]:

arreglo = np.arange(1, 31)

pares = arreglo[arreglo % 2 == 0]

print("arreglo original:", arreglo)
print("Números pares:", pares)

Array original: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Números pares: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


13. Crear dos matrices A (2x3) y B (3x2) y calcular su producto matricial.

In [20]:

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.dot(A, B)  

print("Matriz A:")
print(A)

print("\nMatriz B:")
print(B)

print("\nProducto A x B:")
print(C)

Matriz A:
[[1 2 3]
 [4 5 6]]

Matriz B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Producto A x B:
[[ 58  64]
 [139 154]]


14. Crear una matriz 4x4 con números aleatorios entre 0 y 1. Mostrar el valor máximo y el mínimo

In [ ]:

matriz = np.random.rand(4, 4)

print("Matriz:")
print(matriz)

# Obtener máximo y mínimo
maximo = np.max(matriz)
minimo = np.min(matriz)

print("\nValor máximo:", maximo)
print("Valor mínimo:", minimo)

MAtriz: [[0.23652746 0.819635   0.3275842  0.66428813]
 [0.48429882 0.96124631 0.36275121 0.85909606]
 [0.57427246 0.39879544 0.08581578 0.69763706]
 [0.50197844 0.74484089 0.81274704 0.15798591]]

Valor máximo: 0.9612463142564158
Valor mínimo: 0.08581577995218981


15. Dado el array [10,20,30,40,50], normalizar los valores usando (valor - minimo) / (maximo - minimo)

In [25]:


array = np.array([10,20,30,40,50])

minimo = np.min(array)
maximo = np.max(array)

normalizado = (array - minimo) / (maximo - minimo)

print(normalizado)

[0.   0.25 0.5  0.75 1.  ]


16. Crear un array con 10 números aleatorios entre 1 y 100. Mostrar el array original y el array ordenado.

In [26]:
array = np.random.randint(1, 101, 10)

ordenado = np.sort(array)

print("Original:", array)
print("Ordenado:", ordenado)

Original: [76 94 50 56 42 20 49 22 93 56]
Ordenado: [20 22 42 49 50 56 56 76 93 94]


17. Dado el array [1,2,2,3,3,3,4,4,4,4], calcular cuántas veces aparece cada número

18. Crear la matriz [[1,2,3],[4,5,6]] y calcular su transpuesta.

In [5]:
arreglo1= np.array([[1,2,3],[4,5,6]])
print(arreglo1)

transp= arreglo1.T

print(transp)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


19. Dados A=[5,10,15,20] y B=[3,10,18,20], crear un array booleano indicando en qué posiciones son
iguales

In [28]:
A = np.array([5,10,15,20])
B = np.array([3,10,18,20])

comparacion = A == B

print(comparacion)

[False  True False  True]


20. Crear una matriz 5x3 con números aleatorios entre 1 y 50 y calcular el promedio de cada columna.
TP 1 – Numpy

In [30]:
matriz = np.random.randint(1, 51, (5,3))

promedio_columnas = np.mean(matriz, axis=0)

print("Matriz:")
print(matriz)

print("Promedio por columna:", promedio_columnas)

Matriz:
[[18 23 20]
 [ 9 25 38]
 [37 38 14]
 [24 28 19]
 [47  6 41]]
Promedio por columna: [27.  24.  26.4]
