In [1]:
import numpy as np

# EJEMPLO 1

In [2]:
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)

[1 2 3 4 5]


# EJEMPLO 2

In [ ]:
lista_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2D = np.array(lista_2D)
print(array_2D)

# EJEMPLO 3
- Forma, domension, tipo de datos

In [ ]:
array_2D.shape
array_2D.size
array_2D.dtype


# EJEMPLO 4 
- Utilizar la funcion zeros para cear un array de 3x2
- Utilizar la funcion ones para crear un array de 3x3
- Utilizar la funcion empty para crear un array de 2x4

In [ ]:

np.zeros((3,))
np.ones((3,3))
np.empty((2,4))


array([[4.67296746e-307, 1.69121096e-306, 7.56604561e-307,
        1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.29061142e-306]])

# EJEMPLO 5
- Crear un array de 1 dimension con los valores del 0 al 9
- Crear un array de 2 dimension con la forma 2x5 los valores deben ser del 0 al 9


In [6]:
np.arange(10)
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# EJEMPLO 6
- usar arange para crear array con valores del 10 al 20 y deben ser de dos en dos

In [ ]:
np.arange(10, 20, 2)

# EJEMPLO 7
- Usar linspace para crear un array con valores enteros del 10 al 30

In [ ]:
np.linspace(10,30,10)

# EJEMPLO 8
- Usar linspace para crear un array con 100 numeros del 0 a 3pi

In [ ]:
from numpy import pi

np.linspace(0, 3*pi, 100)

# EJEMPLO 9
- Sumar dos arreglos unidimensionales utilizando linspace
- concatenar los dos arreglos
- Ordenar los valores del nuevo array

In [ ]:
a = np.linspace(10, 20, 6)
b = np.linspace(5, 25, 6)
suma = a + b
print(a)
print(b)
print(suma)

In [ ]:
c = np.concatenate((a,b))
print(c)

In [ ]:
c.sort()
print(c)

# EJEMPLO 10
- Utilizar random para generar 100 numeros entre 0 y 1

In [ ]:
np.random.random(100)

# EJEMPLO 11
- Usar choice para generar 10 numeros aleatorios sin repetir entre 0 y 25

In [ ]:
np.random.choice(26, size=10, replace=False)

# EJEMPLO 12
- Buscar el min, max, promedio, desvio estandar y suma de una lista random de enteros entre 0 y 20 de 10 numeros

In [ ]:
q = np.random.random_integers(20, size=10)
print(min(q))
print(max(q))
print(q.mean())
print(q.std())
print(q.sum())

# EJEMPLO 12
- Encontrar el min y el max en un arrglo bidimensional de 5x4 con numeros del 0 al 20

In [ ]:
p = np.random.random_integers(20, size=(5,4))
print(p)
print(p.mean())
print(p.min(axis=0))
print(p.max(axis=1))
print(p.min())
print(p.max())

# EJEMPLO 13
- Encontar los valores menores a 10 del arreglo anterior

In [ ]:
p<10


# EJEMPLO 14
- Apilamiento vertical y horizontal

In [ ]:
u = np.random.random_integers(20, size=(5,4))
print(u)
v = np.random.random_integers(20, size=(5,4))
print(v)
print(np.vstack((u,v)))
print(np.hstack((u,v)))

# EJEMPLO 15
- Seleccionar los primeros 6 valores de un array de enteros
- Seleccionar los valores de la posicion 0, 2  y 4 del arreglo
- Seleccionar todos los valores con un indice par 

In [ ]:
j= np.random.random_integers(20, size=(10))
print(j)
j[0:6]

In [ ]:
j[0:6:2]

In [ ]:
j[::2]

# EJEMPLO 16
- Seleccionar el cuarto valor en el segundo array de un arreglo de 20 numeros de 8x5
- Seleccionar el segundo valor en los arrays con indice  3, 4 y 5
- Seleccionar los 2 primeros valores con indice 4, 5 y 6 

In [ ]:
arreglo_2d = np.random.random_integers(20, size=(8, 5))
print(arreglo_2d)
arreglo_2d[1, 3]

In [ ]:
arreglo_2d[3:6, 1]

In [ ]:
arreglo_2d[4:7, 0:2]