In [1]:
import numpy as np

In [2]:

# Crear un array
a = np.array([1, 2, 3, 4, 5])

# Sumar 10 a cada elemento
b = a + 10

print("Array original:", a)
print("Array + 10:", b)

Array original: [1 2 3 4 5]
Array + 10: [11 12 13 14 15]


In [3]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
matriz = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np

arreglo1= np.array([[1,4,5,7,8], [34,56,7,8,8]])

print(arreglo1)

[[ 1  4  5  7  8]
 [34 56  7  8  8]]


In [11]:
np.empty((3,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])